### ISSUE TITLE
SSO login reports wrong device type

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-mobile#100]
The Login with Google (or SSO) report Android as a browser even on an iOS:

![image](https://user-images.githubusercontent.com/1633368/106651090-ac301f00-6561-11eb-940e-881a09cc3c83.png)

This can be quite confusing since this is a security feature.

**Comment by marandaneto** [comment]
related to: https://github.com/getsentry/sentry-mobile/blob/ca8bd871f7abd0acc2d4027eeabee6d29532cbff/lib/screens/login/login_web_view.dart#L47-L50

**Comment by denrase** [comment]
Relates to #9

**Comment by marandaneto** [comment]
I'll close as a dup then.
