### ISSUE TITLE
Polishing Tasks v3

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-mobile#101]
## Leftovers
- [x] The Empty Screen (when pull to refresh) shouldn't show a full-page spinner, instead, it should show the content with one card and all the loading indicators in there

## Easy Changes
- [x] Top Card: When reloading, the version first flashes with the full version and then with the shortened one
- [x] Settings Screen: Remove user id / hash in front of email address
- [x] Time offset for releases? Web shows 4 hours ago, the app shows 5 hours ago. Is this a timezone issue? Should use users device timezone not UTC

## Larger Changes

Generally, we want that all data, everything we show is based on session data. No more special requests to fetch issues or Apdex (for now).

That has some changes:
- [x] Change timeframe to 24h for all charts (12h is to small of a resolution)

The charts section should contain 4 charts now: [Reuse color from release page] Also rename the title of charts to "Sessions" so it is clear what the charts represent
- [x] Healthy Sessions
- [x] Error Sessions
- [x] Abnormal Sessions: Show for every platform except javascript and Node
- [x] Crashed Sessions

### Changes to the top card:
- [x] Put platform icon on the top right corner of the card (potentially in a white circle)
- [x] Card: Version number (release) should move besides the time label (Hours Ago)
- [x] Where we show the version now it should say: Total Session: 331253 in the last 24h

### Statistics Changes:
- [x] Crashfree: if the change is exactly 0 we shouldn't show the number with an arrow
- [x] Remove Apdex
- [x] Add Crash Free Sessions [Similar to release detail page in web]
- [x] Add Crash Free Users [Similar to release detail page in web]

### Changes to keep in mind, need to be discussed:
- [ ] Only show projects with Session data -> If no session data we should tell users to upgrade or use an SDK that support sessions
- [x] Move bookmarked projects to the front 
- [x] Swipe to right to load all projects

**Comment by denrase** [comment]
Two more tasks we talked about @HazAT:

- [ ] Center top project cards
- [ ] Fixed left/right insets for session charts

**Comment by matejminar** [comment]
Looks like some of these platform icons assume white default fill, @denrase can you please take a look?
![IMG_096229EA9740-1](https://user-images.githubusercontent.com/9060071/107940844-25c80400-6f89-11eb-908e-406b90eb4682.jpeg)

**Comment by denrase** [comment]
@HazAT Regarding the `Only show projects with Session data`: Do we have a better idea of how to implement this?

**Comment by matejminar** [comment]
@denrase maybe we could fetch something like this and then filter accordingly?
```
/api/0/organizations/sentry/sessions/?project=-1&field=sum(session)&groupBy=project&interval=90d&statsPeriod=90d
```

**Comment by denrase** [comment]
Closing up shop here, as we should have everything that was discussed here. We can open up a new issue for the next feedback round.
