### ISSUE TITLE
App's package has changed to 'io.sentry.mobile.app' but source code package is still 'io.sentrymobile.app'

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-mobile#117]
Let's rename the source folder too
https://github.com/getsentry/sentry-mobile/tree/main/android/app/src/main/kotlin/io/sentrymobile/app

this would mark the App's frames as inApp=false and would affect grouping since we rely on the App's package by default

**Comment by denrase** [comment]
Hey! We used a different prefix because of this issue: https://github.com/getsentry/sentry-mobile/pull/23#issuecomment-733034103

Is this still an issue for us?

**Comment by marandaneto** [comment]
that's a very good point, totally forgot about it, but we still have an issue, our App's package (gotten automatically and used to mark inApp frames) is different than the actual package (source code) and this will cause the issue mentioned above.

**Comment by marandaneto** [comment]
maybe we should add this as an exception to the Java SDK
https://github.com/getsentry/sentry-java/blob/4b8b7d7d11e216153ec7fd2619490894db02ef7e/sentry/src/main/java/io/sentry/SentryStackTraceFactory.java#L40-L44

also `io.sentry.mobile` as we do with the samples, so it'd be fine to do the renaming

**Comment by denrase** [comment]
Sounds good, i will do the rename. Should i also afterwards create a the PR for sentry-java adding `io.sentry.mobile.` as an exception?

**Comment by marandaneto** [comment]
> Sounds good, i will do the rename. Should i also afterwards create a the PR for sentry-java adding `io.sentry.mobile.` as an exception?

that would be nice :)

**Comment by denrase** [comment]
@marandaneto I created https://github.com/getsentry/sentry-java/pull/1283. Checks are still running and i had some other unrelated tests failing with my local setup, it's all documented in the PR.

**Comment by marandaneto** [comment]
@denrase just approved it, we'll look into the JRE 15 issues, be aware that Android is only Java <= 8 compatible, so having a Java 8 JRE is a must.

**Comment by denrase** [comment]
@marandaneto Is this already released in the Java package so that we can merge #120?

**Comment by marandaneto** [comment]
yes, see this https://github.com/getsentry/sentry-mobile/pull/120#issuecomment-801898667

**Comment by denrase** [comment]
Ah yes, could have clicked once more. 🤦 Anyway, i will merge this after null-safety then. Thanks!
