### ISSUE TITLE
Scanning QR Code fails

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry-mobile#136]
After installing the APK, I tried to scan the QR from the [mobila-app](https://sentry.io/settings/account/api/mobile-app/).
It failed to scan and the page is now stuck on Sessions with the message "Error - Something went wrong. Please try again" and a "Retry" button. Nothing works.

If I press on the gear, I can then sign out.
I also tried to paste the token but it also fails.

**Comment by denrase** [comment]
This should be resolved once #141 is merged.

**Comment by armenzg** [comment]
This is still not fixed for me.
How do I update the app?

**Comment by armenzg** [comment]
This is still happening.

**Comment by HazAT** [comment]
I think it might be a problem with the created auth token
https://sentry.io/organizations/sentry/issues/2267488633/?project=5645511&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3Ame_or_none

**Comment by armenzg** [comment]
My initial report was based on version 14.
After installing version 18 I get this:
![image](https://user-images.githubusercontent.com/44410/110977421-26f21400-8330-11eb-97ad-dd8d4507defc.png)

**Comment by denrase** [comment]
Should be fixed with #167, new build is coming soon.

**Comment by denrase** [comment]
@armenzg Could you check with Version `1.0.1 (19)` if you are still experiencing issues?

**Comment by armenzg** [comment]
It works now. Thank you!
