### ISSUE TITLE
Onboarding Issues

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-mobile#138]
https://sentry.io/organizations/sentry-sdks/issues/2232813902/?project=5555613&query=is%3Aunresolved

**Comment by HazAT** [comment]
These are related https://github.com/getsentry/sentry-mobile/issues/130 or even duplicate

**Comment by denrase** [comment]
- Bug reported in sentry
- No smooth transition to last page (image loading blocking ui?)
