### ISSUE TITLE
Evaluate enable/disable and deferred init of Sentry SDK

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-mobile#155]
This is a followup on the undefined/untested SDK behaviour mentioned by @marandaneto here: https://github.com/getsentry/sentry-mobile/pull/153#discussion_r585551303 and here https://github.com/getsentry/sentry-mobile/pull/153#discussion_r585552456 and also documented here https://develop.sentry.dev/sdk/unified-api/#static-api.

Since we ask the user for consent to enable the Sentry SDK during the onboarding, we need to make sure everything works as intended. Also, users have the option to opt in and out of crash detection in settings.

- Check deferred init
- Check enabling/disabling of the SDK during runtime.

/cc @HazAT

**Comment by marandaneto** [comment]
@denrase should we close this?

**Comment by denrase** [comment]
I'll check the session event tomorrow in the morning once more and then close this issue.

**Comment by denrase** [comment]
@marandaneto So i did test this again. Also uncovered a bug while at it that i fixed #170.

So i deleted the application and installed it. Enabled the SDK in onboarding. To me it appeared that the session was visible on sentry.io under releases.

<img width="264" alt="Bildschirmfoto 2021-03-16 um 14 02 24" src="https://user-images.githubusercontent.com/3984453/111314352-9aae5c80-8661-11eb-929b-6c007120f008.png">

Also see it in `https://sentry.io/api/0/organizations/sentry-sdks/sessions/?project=5555613&statsPeriod=24h&interval=1h&field=sum(session)&field=count_unique(user)&groupBy=session.status`

**Comment by marandaneto** [comment]
@denrase I believe we should close this now then?
