### ISSUE TITLE
InApp Rating/Review Link & Alert

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-mobile#194]
We could think about asking for ratings or at least provide a link to the rating screen in the app stores. This way we can get feedback from users and, provided users rate the app positively, improve our ranking in the search.

What do you think @HazAT ?

**Comment by ueman** [comment]
There are In-App-Review-APIs available for [Android](https://developer.android.com/guide/playcore/in-app-review) and [iOS](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/). [This Flutter package](https://pub.dev/packages/in_app_review), for example, combines them for Flutter.
