### ISSUE TITLE
Code generation is broken: `Could not generate `toJson` code for `stats24h` because of type `Stat`.`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-mobile#199]
```
➜  sentry-mobile git:(main) flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 373ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 81ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 433ms

[INFO] Running build...
[INFO] Running build completed, took 21ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 51ms

[SEVERE] json_serializable:json_serializable on lib/types/stats.dart (cached):

Could not generate `toJson` code for `stats24h` because of type `Stat`.
package:sentry_mobile/types/stats.dart:14:21
   ╷
14 │   final List<Stat>? stats24h;
   │                     ^^^^^^^^
   ╵
```

**Comment by ueman** [comment]
The generated files shouldn't be committed to the repository because they might become stale. Just like this issue shows.
Instead they should be generated on CI on each run.
Same thing for local builds.
That behavior would have broken CI for this issue (and rightly so).

**Comment by bruno-garcia** [comment]
@ueman PR incoming? :P

**Comment by ueman** [comment]
> @ueman PR incoming? :P

@denrase is not fully convinced yet: https://github.com/getsentry/sentry-mobile/pull/204#issuecomment-874093102

**Comment by bruno-garcia** [comment]
To be honest I thought the same as @denrase.

One alternative is to keep files there but in CI generate them and make sure they match. Break CI if they don't so someone has to intervene.

**Comment by denrase** [comment]
@bruno-garcia Decided to exclude the files after all. The command runs fast and we don't need to do anything special on CI. We can revert back if this turns out to be tedious.
