### ISSUE TITLE
Integrate Flutter SDK - Notes

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-mobile#22]
# Integrate Flutter SDK - Notes
- From the release notes, went to https://pub.dev/packages/sentry_flutter
- Copied version from there, to pubspec.yaml. Worked as expected
- Used the DSN from the sample for now, just to see what happens.
- Run on an Android device, get the following error:
	```
	D/Sentry  (14587): java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
	...
	```
- First question that pups to mind: What is this error and is it checking if the device is rooted (see Whole StackTrace below)? Ignore and move on.
- Many debug logs appear in the console, is this the same on other platforms? The result is that i don't known which of these are just normal and to which i need to pay attention to as a application developer or integrator:
	```
	D/Sentry  (14587): UncaughtExceptionHandlerIntegration enabled: true
	D/Sentry  (14587): default UncaughtExceptionHandler class='com.android.internal.os.RuntimeInit$KillApplicationHandler'
	D/Sentry  (14587): UncaughtExceptionHandlerIntegration installed.
	...
	```
- Like this one:
	```
	I/Sentry  (14587): No permission (ACCESS_NETWORK_STATE) to check network status.
	D/Sentry  (14587): Request failed, API returned 403
	...
	```
- My first guess would be that i missed some permission in the Android Manifest. The stacktrace proceeds to show html code, which is not particularly helpful at this point.
- Ok, next step is to use my real DSN. Since i only integrated the SDK once, i'm not immediatley aware of where to get it, but i got the info `Sign up for a Sentry.io account and get a DSN at http://sentry.io.`. This is good, as i have a reference where i should go. Was already logged in and went to settings. So many points, used the search, and immediatley found it. Good experierience. Maybe we could route logged in users directly to this DSN project picker.
- The http error is gone, so this was probably the dummy dsn url that i used. There is still the permission error. It does not say specifically that this is an Android thing, so only a nAndroid developer would know about it immediately. I have no indication if the SentrySDK really needs this, but i'm just gonna try to add the permission. Went to the docs to get more info: https://developer.android.com/reference/android/Manifest.permission#ACCESS_NETWORK_STATE and added it with `<permission android:name="android.permission.ACCESS_NETWORK_STATE"/>` in the main AndroidManifest.xml
- Which was worng, because it the correct definition is `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>` :facepalm
- Also found this issue with a google search which explains the error neatly: https://github.com/getsentry/sentry-android/issues/295
- Trying on an iOS device, i have no console output. But this may be a configuration issue with my setup. Using Android Studio with the Flutter/Dart Plugins.
- This seems to be a flutter issue with iOS 13+ https://github.com/flutter/flutter/issues/41133, https://github.com/flutter/flutter/pull/66399. Not seeing anything in simulator either
- Ok, got some logs working with `flutter run` and openening the observatory in the browser. Don't see sentry stuff from startup, but saw some other logs from the application. This is something i need to figure out, will ignore for now and move on to testing the sdk.
- This concludes the install experience.

## Whole Android device startup console output:

```
I/Sentry  (14587): Initializing SDK with DSN: 'https://example@sentry.io/add-your-dsn-here'
I/Sentry  (14587): sentry-debug-meta.properties file was not found.
I/Sentry  (14587): GlobalHubMode: 'true'
D/Sentry  (14587): SU doesn't exist.
D/Sentry  (14587): java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
D/Sentry  (14587): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
D/Sentry  (14587): 	at java.lang.Runtime.exec(Runtime.java:699)
D/Sentry  (14587): 	at java.lang.Runtime.exec(Runtime.java:564)
D/Sentry  (14587): 	at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135)
D/Sentry  (14587): 	at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90)
D/Sentry  (14587): 	at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114)
D/Sentry  (14587): 	at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102)
D/Sentry  (14587): 	at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2)
D/Sentry  (14587): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D/Sentry  (14587): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D/Sentry  (14587): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D/Sentry  (14587): 	at java.lang.Thread.run(Thread.java:923)
D/Sentry  (14587): Caused by: java.io.IOException: error=2, No such file or directory
D/Sentry  (14587): 	at java.lang.UNIXProcess.forkAndExec(Native Method)
D/Sentry  (14587): 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
D/Sentry  (14587): 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
D/Sentry  (14587): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
D/Sentry  (14587): 	... 11 more
D/Sentry  (14587): UncaughtExceptionHandlerIntegration enabled: true
D/Sentry  (14587): default UncaughtExceptionHandler class='com.android.internal.os.RuntimeInit$KillApplicationHandler'
D/Sentry  (14587): UncaughtExceptionHandlerIntegration installed.
D/Sentry  (14587): SendCachedEventFireAndForgetIntegration installed.
D/Sentry  (14587): NdkIntegration enabled: false
D/Sentry  (14587): Registering EnvelopeFileObserverIntegration for path: /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox
D/Sentry  (14587): Started processing cached files from /data/user/0/io.sentry.sentry_mobile/cache/sentry
D/Sentry  (14587): Processing dir. /data/user/0/io.sentry.sentry_mobile/cache/sentry
D/Sentry  (14587): EnvelopeFileObserverIntegration installed.
D/Sentry  (14587): SendCachedEventFireAndForgetIntegration installed.
D/Sentry  (14587): AnrIntegration enabled: true
D/Sentry  (14587): Processing 0 items from cache dir /data/user/0/io.sentry.sentry_mobile/cache/sentry
D/Sentry  (14587): ANR timeout in milliseconds: 5000
D/Sentry  (14587): File /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox is not a File.
D/Sentry  (14587): Finished processing cached files from /data/user/0/io.sentry.sentry_mobile/cache/sentry
D/Sentry  (14587): AnrIntegration installed.
D/Sentry  (14587): Started processing cached files from /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox
D/Sentry  (14587): enableSessionTracking enabled: true
D/Sentry  (14587): enableAppLifecycleBreadcrumbs enabled: true
D/Sentry  (14587): Processing dir. /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox
D/Sentry  (14587): Processing 0 items from cache dir /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox
D/Sentry  (14587): Finished processing cached files from /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox
D/Sentry  (14587): AppLifecycleIntegration installed.
D/Sentry  (14587): ActivityBreadcrumbsIntegration enabled: true
D/Sentry  (14587): ActivityBreadcrumbsIntegration installed.
D/Sentry  (14587): AppComponentsBreadcrumbsIntegration enabled: true
D/Sentry  (14587): AppComponentsBreadcrumbsIntegration installed.
D/Sentry  (14587): SystemEventsBreadcrumbsIntegration enabled: true
D/Sentry  (14587): SystemEventsBreadcrumbsIntegration installed.
D/Sentry  (14587): enableSystemEventsBreadcrumbs enabled: true
I/Sentry  (14587): TYPE_AMBIENT_TEMPERATURE is not available.
D/Sentry  (14587): enableSystemEventBreadcrumbs enabled: true
D/Sentry  (14587): Adding Envelope to offline storage: /data/user/0/io.sentry.sentry_mobile/cache/sentry/ef35cd33-0bf0-4180-acdf-e0d6a0c1247b.envelope
I/TetheringManager(14587): registerTetheringEventCallback:io.sentry.sentry_mobile
I/TetheringManager(14587): registerTetheringEventCallback:io.sentry.sentry_mobile
I/Sentry  (14587): No permission (ACCESS_NETWORK_STATE) to check network status.
D/Sentry  (14587): Request failed, API returned 403
D/Sentry  (14587): <!DOCTYPE html>
D/Sentry  (14587): <html lang="en">
D/Sentry  (14587):     <head>
D/Sentry  (14587):         <meta http-equiv="content-type" content="text/html; charset=utf-8">
D/Sentry  (14587):         <meta name="robots" content="NONE,NOARCHIVE">
D/Sentry  (14587):         <link href="https://s1.sentry-cdn.com/_static/5e7eb8be47d7d371f04228114fe520c9/sentry/images/favicon.ico" rel="shortcut icon" type="image/png"/>
D/Sentry  (14587):         <link href="https://s1.sentry-cdn.com/_static/5e7eb8be47d7d371f04228114fe520c9/sentry/dist/getsentry.css" rel="stylesheet" type="text/css" />
D/Sentry  (14587): 
D/Sentry  (14587):         <title>CSRF Verification Failed | Sentry</title>
D/Sentry  (14587): 
D/Sentry  (14587):     </head>
D/Sentry  (14587): 
D/Sentry  (14587):     <body>
D/Sentry  (14587): 
D/Sentry  (14587): 
D/Sentry  (14587):         <header>
D/Sentry  (14587):             <div class="container">
D/Sentry  (14587):                 <div class="pull-left">
D/Sentry  (14587):                     <a href="/" id="logo"><img src="https://s1.sentry-cdn.com/_static/5e7eb8be47d7d371f04228114fe520c9/getsentry/images/logo.png" /></a>
D/Sentry  (14587):                 </div>
D/Sentry  (14587):             </div>
D/Sentry  (14587):         </header>
D/Sentry  (14587): 
D/Sentry  (14587):         <section id="content">
D/Sentry  (14587): 
D/Sentry  (14587):             <div class="container">
D/Sentry  (14587):                 <div class="page-header">
D/Sentry  (14587):                     <h2>CSRF Verification Failed</h2>
D/Sentry  (14587):                 </div>
D/Sentry  (14587): 
D/Sentry  (14587):                 <p>A required security token was not found or was invalid.</p>
D/Sentry  (14587): 
D/Sentry  (14587):                 <p>If you're continually seeing this issue, try the following:</p>
D/Sentry  (14587): 
D/Sentry  (14587):                 <ol>
D/Sentry  (14587):                   <li>Clear cookies (at least for Sentry's domain).</li>
D/Sentry  (14587):                   <li>Reload the page you're trying to submit (don't re-submit data).</li>
D/Sentry  (14587):                   <li>Re-enter the information, and submit the form again.</li>
D/Sentry  (14587):                 </ol>
D/Sentry  (14587): 
D/Sentry  (14587):                 
D/Sentry  (14587):                   <p>You are seeing this message because Sentry requires a 'Referer
D/Sentry  (14587):                    header' to be sent by your Web browser, but none was sent. This header is
D/Sentry  (14587):                    required for security reasons, to ensure that your browser is not being
D/Sentry  (14587):                    hijacked by third parties.</p>
D/Sentry  (14587): 
D/Sentry  (14587):                   <p>If you have configured your browser to disable 'Referer' headers, please
D/Sentry  (14587):                    re-enable them, at least for this site, or for HTTPS connections, or for
D/Sentry  (14587):                    'same-origin' requests.</p>
D/Sentry  (14587):                 
D/Sentry  (14587): 
D/Sentry  (14587):                 <p>Read more about <a href="https://en.wikipedia.org/wiki/Cross-site_request_forgery">CSRF on Wikipedia</a>.</p>
D/Sentry  (14587): 
D/Sentry  (14587):                 <div class="page-header">
D/Sentry  (14587):                     <h3>System Status</h3>
D/Sentry  (14587):                 </div>
D/Sentry  (14587): 
D/Sentry  (14587):                 <p><strong><span id="official-system-status"></span></strong></p>
D/Sentry  (14587): 
D/Sentry  (14587):                 <p>If our status page says we're up but something is clearly wrong, <a href="mailto:support@sentry.io">let us know</a> what you're seeing.</p>
D/Sentry  (14587): 
D/Sentry  (14587):                 <script type="text/javascript" src="https://statuspage-production.s3.amazonaws.com/se.js"></script>
D/Sentry  (14587):                 <script type="text/javascript">
D/Sentry  (14587):                   window.fetchStatusPage({
D/Sentry  (14587):                     pageId: 't687h3m0nh65',
D/Sentry  (14587):                     renderTo: '#official-system-status'
D/Sentry  (14587):                   });
D/Sentry  (14587):                 </script>
D/Sentry  (14587): 
D/Sentry  (14587):             </div>
D/Sentry  (14587): 
D/Sentry  (14587):         </section>
D/Sentry  (14587):     </body>
D/Sentry  (14587): </html>
D/Sentry  (14587): The transport failed to send the envelope with response code 403
E/Sentry  (14587): Envelope submission failed
E/Sentry  (14587): java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
E/Sentry  (14587): 	at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:249)
E/Sentry  (14587): 	at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
E/Sentry  (14587): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/Sentry  (14587): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/Sentry  (14587): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Sentry  (14587): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Sentry  (14587): 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by marandaneto** [comment]
> # Integrate Flutter SDK - Notes
> * From the release notes, went to https://pub.dev/packages/sentry_flutter
> * Copied version from there, to pubspec.yaml. Worked as expected
> * Used the DSN from the sample for now, just to see what happens.
> * Run on an Android device, get the following error:
>   ```
>    D/Sentry  (14587): java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
>    ...
>   ```

as you did run a debug version of the app, the SDK detects it's a debug build and enables the `debug` mode of the SDK automatically, this is just a debug log btw, which tries to detect if the device is ROOTED or not.

> * First question that pups to mind: What is this error and is it checking if the device is rooted (see Whole StackTrace below)? Ignore and move on.

true, we should not log the whole stack trace, this could be improved with a more friendly message.
https://github.com/getsentry/sentry-java/pull/1059

> * Many debug logs appear in the console, is this the same on other platforms? The result is that i don't known which of these are just normal and to which i need to pay attention to as a application developer or integrator:
>   ```
>    D/Sentry  (14587): UncaughtExceptionHandlerIntegration enabled: true
>    D/Sentry  (14587): default UncaughtExceptionHandler class='com.android.internal.os.RuntimeInit$KillApplicationHandler'
>    D/Sentry  (14587): UncaughtExceptionHandlerIntegration installed.

by default, `debug` level is enabled if `debug` mode is enabled, but you can configure this and get only relevant logs based on the configured level.

https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/sentry_options.dart#L97-L104

>    ...
>   ```
> * Like this one:
>   ```
>    I/Sentry  (14587): No permission (ACCESS_NETWORK_STATE) to check network status.
>    D/Sentry  (14587): Request failed, API returned 403
>    ...
>   ```

`ACCESS_NETWORK_STATE` true, it's an optional permission, SDK would keep working normally, but it always tries to make a request even if there's no connection, with this permission, if there's no connection, it doesn't even try to make a request, it's just an optimization.

> * My first guess would be that I missed some permission in the Android Manifest. The stacktrace proceeds to show html code, which is not particularly helpful at this point.

yeah, we can just validate the DSN's format, but not if it's really valid and active, this is done only on the backend and usually validated by a 403 if not.
not sure if a better message here could be given as I'd guess 403 is used for other reasons (permission level).

> * Ok, next step is to use my real DSN. Since i only integrated the SDK once, i'm not immediatley aware of where to get it, but i got the info `Sign up for a Sentry.io account and get a DSN at http://sentry.io.`. This is good, as i have a reference where i should go. Was already logged in and went to settings. So many points, used the search, and immediatley found it. Good experierience. Maybe we could route logged in users directly to this DSN project picker.
> * The http error is gone, so this was probably the dummy dsn url that i used. There is still the permission error. It does not say specifically that this is an Android thing, so only a nAndroid developer would know about it immediately. I have no indication if the SentrySDK really needs this, but i'm just gonna try to add the permission. Went to the docs to get more info: https://developer.android.com/reference/android/Manifest.permission#ACCESS_NETWORK_STATE and added it with `<permission android:name="android.permission.ACCESS_NETWORK_STATE"/>` in the main AndroidManifest.xml
> * Which was worng, because it the correct definition is `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>` :facepalm

We used to have this on the Android docs, and I can't find it now, we had a big refactoring on the whole Sentry docs, it might be lost and maybe worth adding it again.

> * Also found this issue with a google search which explains the error neatly: [getsentry/sentry-android#295](https://github.com/getsentry/sentry-android/issues/295)
> * Trying on an iOS device, i have no console output. But this may be a configuration issue with my setup. Using Android Studio with the Flutter/Dart Plugins.
> * This seems to be a flutter issue with iOS 13+ [flutter/flutter#41133](https://github.com/flutter/flutter/issues/41133), [flutter/flutter#66399](https://github.com/flutter/flutter/pull/66399). Not seeing anything in simulator either
> * Ok, got some logs working with `flutter run` and openening the observatory in the browser. Don't see sentry stuff from startup, but saw some other logs from the application. This is something i need to figure out, will ignore for now and move on to testing the sdk.
> * This concludes the install experience.

yep, it needs to be a debug build, we are using `print` on Swift so it doesn't leak to the release App, although Cocoa uses `NSLog` and it should be shown but I'd need to test myself again.

> 
> ## Whole Android device startup console output:
> ```
> I/Sentry  (14587): Initializing SDK with DSN: 'https://example@sentry.io/add-your-dsn-here'
> I/Sentry  (14587): sentry-debug-meta.properties file was not found.
> I/Sentry  (14587): GlobalHubMode: 'true'
> D/Sentry  (14587): SU doesn't exist.
> D/Sentry  (14587): java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
> D/Sentry  (14587): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
> D/Sentry  (14587): 	at java.lang.Runtime.exec(Runtime.java:699)
> D/Sentry  (14587): 	at java.lang.Runtime.exec(Runtime.java:564)
> D/Sentry  (14587): 	at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135)
> D/Sentry  (14587): 	at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90)
> D/Sentry  (14587): 	at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114)
> D/Sentry  (14587): 	at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102)
> D/Sentry  (14587): 	at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2)
> D/Sentry  (14587): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> D/Sentry  (14587): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> D/Sentry  (14587): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> D/Sentry  (14587): 	at java.lang.Thread.run(Thread.java:923)
> D/Sentry  (14587): Caused by: java.io.IOException: error=2, No such file or directory
> D/Sentry  (14587): 	at java.lang.UNIXProcess.forkAndExec(Native Method)
> D/Sentry  (14587): 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
> D/Sentry  (14587): 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
> D/Sentry  (14587): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
> D/Sentry  (14587): 	... 11 more
> D/Sentry  (14587): UncaughtExceptionHandlerIntegration enabled: true
> D/Sentry  (14587): default UncaughtExceptionHandler class='com.android.internal.os.RuntimeInit$KillApplicationHandler'
> D/Sentry  (14587): UncaughtExceptionHandlerIntegration installed.
> D/Sentry  (14587): SendCachedEventFireAndForgetIntegration installed.
> D/Sentry  (14587): NdkIntegration enabled: false
> D/Sentry  (14587): Registering EnvelopeFileObserverIntegration for path: /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox
> D/Sentry  (14587): Started processing cached files from /data/user/0/io.sentry.sentry_mobile/cache/sentry
> D/Sentry  (14587): Processing dir. /data/user/0/io.sentry.sentry_mobile/cache/sentry
> D/Sentry  (14587): EnvelopeFileObserverIntegration installed.
> D/Sentry  (14587): SendCachedEventFireAndForgetIntegration installed.
> D/Sentry  (14587): AnrIntegration enabled: true
> D/Sentry  (14587): Processing 0 items from cache dir /data/user/0/io.sentry.sentry_mobile/cache/sentry
> D/Sentry  (14587): ANR timeout in milliseconds: 5000
> D/Sentry  (14587): File /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox is not a File.
> D/Sentry  (14587): Finished processing cached files from /data/user/0/io.sentry.sentry_mobile/cache/sentry
> D/Sentry  (14587): AnrIntegration installed.
> D/Sentry  (14587): Started processing cached files from /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox
> D/Sentry  (14587): enableSessionTracking enabled: true
> D/Sentry  (14587): enableAppLifecycleBreadcrumbs enabled: true
> D/Sentry  (14587): Processing dir. /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox
> D/Sentry  (14587): Processing 0 items from cache dir /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox
> D/Sentry  (14587): Finished processing cached files from /data/user/0/io.sentry.sentry_mobile/cache/sentry/outbox
> D/Sentry  (14587): AppLifecycleIntegration installed.
> D/Sentry  (14587): ActivityBreadcrumbsIntegration enabled: true
> D/Sentry  (14587): ActivityBreadcrumbsIntegration installed.
> D/Sentry  (14587): AppComponentsBreadcrumbsIntegration enabled: true
> D/Sentry  (14587): AppComponentsBreadcrumbsIntegration installed.
> D/Sentry  (14587): SystemEventsBreadcrumbsIntegration enabled: true
> D/Sentry  (14587): SystemEventsBreadcrumbsIntegration installed.
> D/Sentry  (14587): enableSystemEventsBreadcrumbs enabled: true
> I/Sentry  (14587): TYPE_AMBIENT_TEMPERATURE is not available.
> D/Sentry  (14587): enableSystemEventBreadcrumbs enabled: true
> D/Sentry  (14587): Adding Envelope to offline storage: /data/user/0/io.sentry.sentry_mobile/cache/sentry/ef35cd33-0bf0-4180-acdf-e0d6a0c1247b.envelope
> I/TetheringManager(14587): registerTetheringEventCallback:io.sentry.sentry_mobile
> I/TetheringManager(14587): registerTetheringEventCallback:io.sentry.sentry_mobile
> I/Sentry  (14587): No permission (ACCESS_NETWORK_STATE) to check network status.
> D/Sentry  (14587): Request failed, API returned 403
> D/Sentry  (14587): <!DOCTYPE html>
> D/Sentry  (14587): <html lang="en">
> D/Sentry  (14587):     <head>
> D/Sentry  (14587):         <meta http-equiv="content-type" content="text/html; charset=utf-8">
> D/Sentry  (14587):         <meta name="robots" content="NONE,NOARCHIVE">
> D/Sentry  (14587):         <link href="https://s1.sentry-cdn.com/_static/5e7eb8be47d7d371f04228114fe520c9/sentry/images/favicon.ico" rel="shortcut icon" type="image/png"/>
> D/Sentry  (14587):         <link href="https://s1.sentry-cdn.com/_static/5e7eb8be47d7d371f04228114fe520c9/sentry/dist/getsentry.css" rel="stylesheet" type="text/css" />
> D/Sentry  (14587): 
> D/Sentry  (14587):         <title>CSRF Verification Failed | Sentry</title>
> D/Sentry  (14587): 
> D/Sentry  (14587):     </head>
> D/Sentry  (14587): 
> D/Sentry  (14587):     <body>
> D/Sentry  (14587): 
> D/Sentry  (14587): 
> D/Sentry  (14587):         <header>
> D/Sentry  (14587):             <div class="container">
> D/Sentry  (14587):                 <div class="pull-left">
> D/Sentry  (14587):                     <a href="/" id="logo"><img src="https://s1.sentry-cdn.com/_static/5e7eb8be47d7d371f04228114fe520c9/getsentry/images/logo.png" /></a>
> D/Sentry  (14587):                 </div>
> D/Sentry  (14587):             </div>
> D/Sentry  (14587):         </header>
> D/Sentry  (14587): 
> D/Sentry  (14587):         <section id="content">
> D/Sentry  (14587): 
> D/Sentry  (14587):             <div class="container">
> D/Sentry  (14587):                 <div class="page-header">
> D/Sentry  (14587):                     <h2>CSRF Verification Failed</h2>
> D/Sentry  (14587):                 </div>
> D/Sentry  (14587): 
> D/Sentry  (14587):                 <p>A required security token was not found or was invalid.</p>
> D/Sentry  (14587): 
> D/Sentry  (14587):                 <p>If you're continually seeing this issue, try the following:</p>
> D/Sentry  (14587): 
> D/Sentry  (14587):                 <ol>
> D/Sentry  (14587):                   <li>Clear cookies (at least for Sentry's domain).</li>
> D/Sentry  (14587):                   <li>Reload the page you're trying to submit (don't re-submit data).</li>
> D/Sentry  (14587):                   <li>Re-enter the information, and submit the form again.</li>
> D/Sentry  (14587):                 </ol>
> D/Sentry  (14587): 
> D/Sentry  (14587):                 
> D/Sentry  (14587):                   <p>You are seeing this message because Sentry requires a 'Referer
> D/Sentry  (14587):                    header' to be sent by your Web browser, but none was sent. This header is
> D/Sentry  (14587):                    required for security reasons, to ensure that your browser is not being
> D/Sentry  (14587):                    hijacked by third parties.</p>
> D/Sentry  (14587): 
> D/Sentry  (14587):                   <p>If you have configured your browser to disable 'Referer' headers, please
> D/Sentry  (14587):                    re-enable them, at least for this site, or for HTTPS connections, or for
> D/Sentry  (14587):                    'same-origin' requests.</p>
> D/Sentry  (14587):                 
> D/Sentry  (14587): 
> D/Sentry  (14587):                 <p>Read more about <a href="https://en.wikipedia.org/wiki/Cross-site_request_forgery">CSRF on Wikipedia</a>.</p>
> D/Sentry  (14587): 
> D/Sentry  (14587):                 <div class="page-header">
> D/Sentry  (14587):                     <h3>System Status</h3>
> D/Sentry  (14587):                 </div>
> D/Sentry  (14587): 
> D/Sentry  (14587):                 <p><strong><span id="official-system-status"></span></strong></p>
> D/Sentry  (14587): 
> D/Sentry  (14587):                 <p>If our status page says we're up but something is clearly wrong, <a href="mailto:support@sentry.io">let us know</a> what you're seeing.</p>
> D/Sentry  (14587): 
> D/Sentry  (14587):                 <script type="text/javascript" src="https://statuspage-production.s3.amazonaws.com/se.js"></script>
> D/Sentry  (14587):                 <script type="text/javascript">
> D/Sentry  (14587):                   window.fetchStatusPage({
> D/Sentry  (14587):                     pageId: 't687h3m0nh65',
> D/Sentry  (14587):                     renderTo: '#official-system-status'
> D/Sentry  (14587):                   });
> D/Sentry  (14587):                 </script>
> D/Sentry  (14587): 
> D/Sentry  (14587):             </div>
> D/Sentry  (14587): 
> D/Sentry  (14587):         </section>
> D/Sentry  (14587):     </body>
> D/Sentry  (14587): </html>
> D/Sentry  (14587): The transport failed to send the envelope with response code 403
> E/Sentry  (14587): Envelope submission failed
> E/Sentry  (14587): java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
> E/Sentry  (14587): 	at io.sentry.transport.AsyncConnection$EnvelopeSender.flush(AsyncConnection.java:249)
> E/Sentry  (14587): 	at io.sentry.transport.AsyncConnection$EnvelopeSender.run(AsyncConnection.java:212)
> E/Sentry  (14587): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
> E/Sentry  (14587): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> E/Sentry  (14587): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E/Sentry  (14587): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E/Sentry  (14587): 	at java.lang.Thread.run(Thread.java:923)
> ```

**Comment by marandaneto** [comment]
impressing, thanks for this @denrase 

how would you rate your first experience? how relevant were the captured stack traces on sentry.io? what was your overall feeling?

looking forward to improving all of this!

**Comment by denrase** [comment]
Good so far, except for some confusion regarding the android permissions. Other than that, it just worked out of the vox.
Logging of non-fatals also works so far. I hacked together a debug screen where we can trigger all relevant events and i'm going through all platform/device combinations to verify that everyting is recorded by sentry. Hope to get this done today, will report back.

**Comment by denrase** [comment]
Regarding stacktraces, i see the file and code line where the recorded exception occured. 👌

**Comment by bruno-garcia** [comment]
Great stuff! Thanks for the feedback.

I think we should get rid of that `which` error. Maybe just hide the log.error because it fails on all non rooted devices.
