### ISSUE TITLE
Upgrade sentry_flutter SDK to the latest version

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-mobile#25]
Please also create a new project under the sentry-sdks org and use its own DSN.
It's a bit confusing when different sources are capturing errors under the same project (currently sentry-flutter).
Ideally, it's gonna be called sentry-mobile.

**Comment by denrase** [comment]
@marandaneto @HazAT @bruno-garcia  I do not have permissions to create the `sentry-mobile` project. Could one of you create it? 🙇

**Comment by bruno-garcia** [comment]
I've created a new project:

https://sentry.io/sentry-sdks/sentry-mobile-development/getting-started/flutter/

I've named it `sentry-mobile-development` to be explicit, since once the app is live we'll have it under a different org in Sentry.

**Comment by denrase** [comment]
@bruno-garcia Thank you! 🙇
