### ISSUE TITLE
Initial Feedback

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry-mobile#66]
Hey @denrase, thanks again for the call. As discussed, here are my first initial observations. Let's go over them and we can create individual issues if needed.

- are we respecting the bookmarked projects right now? I think I've seen cards for all projects, not just bookmarked ones
- reorder project cards by latest release
- I have a suspicion that we use project name instead of project slug in settings (let's switch to a slug if that is true)
- nit: rename SignIn to either login or sign in
- I think that we don't need to surface platforms in the project card (we don't do that anywhere in the web app), let's show the environment and relative date instead
- can we add commit faces to the bottom right of the project card? I think they are extremely useful for distinguishing releases on the web where the name is usually just an unreadable hash
- we should not let the platforms affect the position of the line chart, because the visual is less consistent that way (I think this will be solved once we replace platforms with relative date, environment, and commit faces as every release has at least a date)

![Kapture 2021-01-08 at 15 41 09](https://user-images.githubusercontent.com/9060071/104028095-9892d200-51c8-11eb-8d08-67cf9907fc01.gif)

- statistics cards bottom overflow

![Kapture 2021-01-08 at 16 02 25](https://user-images.githubusercontent.com/9060071/104030002-004a1c80-51cb-11eb-93b3-c5b2f3fd683c.gif)

### Things we still need to look into:
- At first, I thought that we don't need the landing screen (we could hop directly onto the dashboard/login screen) but we will try to come up with the help of the design team with few onboarding slides to explain the app
- I am discussing the bookmarking CSRF issue with our security team
- Overall usability and user stories (e.g what if I want to see not just the latest release and do all data we show make sense?)

🚀🚀🚀  Thanks for awesome work so far!  🚀🚀🚀

**Comment by denrase** [comment]
Thanks for the great feedback! 🙇 I agree with everything so far, we should tackle all those things.

As far as bookmarks go. Right now, we show only bookmarks if the user has at least one. If there are none, we show all the projects. Maybe this should be a setting that can be enabled/disabled from the settings. What do you think?

**Comment by denrase** [comment]
I will start creating issues for the obvious points that you have raised.

**Comment by matejminar** [comment]
> As far as bookmarks go. Right now, we show only bookmarks if the user has at least one. If there are none, we show all the projects. Maybe this should be a setting that can be enabled/disabled from the settings. What do you think?

Maybe I'm doing something wrong, but I see cards for all projects even though I have existing bookmarks:

https://user-images.githubusercontent.com/9060071/104191627-04ba4380-541e-11eb-87b1-db1706065241.mp4

**Comment by denrase** [comment]
Just saw it, you are right. This is a regression, will create an issue for it. 🙇

**Comment by denrase** [comment]
Last issue from the list here is handled in #90. Closing.
