### ISSUE TITLE
Enha(cards): Reorder project cards by latest release

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-mobile#67]
Reates to #66

**Comment by denrase** [comment]
@matejminar Seems that we can't do that at the moments, as we have no infos about the release dates when fetching projects that i am aware of.

```
"latestRelease": {
  "version": "c55ebd16b42f52209529a5899b1a3ea570c52d62"
}
```

We would have to fetch all releases again before displaying any cards, which takes a long time when there are many.

**Comment by matejminar** [comment]
ok, let's leave as is for now

**Comment by denrase** [comment]
Slosing as the overall objective moved to sessions instead of individual releases.
