### ISSUE TITLE
Needed Config. before releasing

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-mobile#80]
on Android, we'd need to talk about supported OS versions= minSdkVersion, package name= applicationId and signingConfig

https://github.com/getsentry/sentry-mobile/blob/main/android/app/build.gradle#L41-L42
https://github.com/getsentry/sentry-mobile/blob/main/android/app/build.gradle#L49-L53

The same would need to be done on iOS, at least the package name=bundleId and probably a few other extra configurations, those things can't be changed after released (eg package name and signingConfig).

https://github.com/getsentry/sentry-mobile/blob/main/ios/Runner/Info.plist#L14

**Comment by denrase** [comment]
@marandaneto We already created the iOS `Bundle-ID` with `io.sentry.mobile.app` and will also use this for Android `applicationId `. Setup tasks will follow.
